name: dev
version: "3.9"
services:
  httpbin:
    image: mccutchen/go-httpbin:v2.15.0
    environment:
      - MAX_BODY_SIZE=15728640 # 15 MiB
    command: [ "/bin/go-httpbin", "-port", "8081" ]
    ports:
      - "8081:8081"
  haproxy:
    restart: unless-stopped
    image: haproxy:lts-alpine3.21
    ports: [ "8080:80", "8443:443", "8082:8082" ,"9000:9000", "9001:9001","9002:9002"]
    depends_on:
      - httpbin
    volumes:
      - type: bind
        source: ./haproxy/
        target: /usr/local/etc/haproxy
    environment:
      - BACKEND_HOST=httpbin:8081
    extra_hosts:
      - "host.docker.internal:host-gateway" # for haproxy to resolve host.docker.internal
